### ISSUE TITLE
Install the latest version of Chrome on Travis.

### ISSUE THREAD

**Issue by zdfs** [LeaVerou/bliss#117]
Seems related to #109. I will fork a branch and see what I can do to get this working.

**Comment by dperrymorrow** [comment]
is there a way to get travis to run multiple browsers? or is that only meaningfull if we start distributing a polyfill package #108

**Comment by praveenpuglia** [comment]
Well this doesn't look good! - https://twitter.com/domenic/status/502571560944021506

**Comment by zdfs** [comment]
Yeah and another issue is that even if I do figure it out, it will add a substantial amount of time to the build.

**Comment by zdfs** [comment]
Installing a specific version of Firefox is much easier, it seems like: https://docs.travis-ci.com/user/ci-environment/#Firefox

**Comment by zdfs** [comment]
Finally found the issue of why Chromium browser is stuck on version 37: https://github.com/travis-ci/travis-ci/issues/3475

**Comment by zdfs** [comment]
I have it working, seems a little crazy for the `.travis.yml`. https://travis-ci.org/LeaVerou/bliss/jobs/96878563

**Comment by zdfs** [comment]
Takes the build up to 3+ minutes.

**Comment by zdfs** [comment]
There might be some steps we can take out too. I just copied from some place that seemed to have it worked out.

**Comment by praveenpuglia** [comment]
I kind of did hit and trial and got Chrome 47 working. :)
https://travis-ci.org/praveenpuglia/bliss/jobs/96882573

**Comment by praveenpuglia** [comment]
Let me know if what I did is correct solves the problem. If you wish I can send the PR for it. :)

**Comment by zdfs** [comment]
So the only question I have from https://github.com/praveenpuglia/bliss/blob/th-test/.travis.yml is why do we need `https://github.com/praveenpuglia/bliss/blob/th-test/.travis.yml`?

Other than that, I say yeah, submit a PR for it. I'll delete my branch. Good job.

**Comment by praveenpuglia** [comment]
oh you don't. I did it just to test the commit with my own travis build. let me send a PR. Thanks! :)

**Comment by zdfs** [comment]
Sorry, I meant `- sudo apt-get install -y libappindicator1 fonts-liberation`

**Comment by praveenpuglia** [comment]
Okay. When I did normal installation, it failed with error indicating those packages were chrome dependencies and could not be found.

**Comment by zdfs** [comment]
Ok. Just making sure.

**Comment by fulls1z3** [comment]
Hope it helps:

```
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "6"
cache:
  directories: node_modules
branches:
  only: master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g npm@^3
  - sleep 3
```
